from lib.config import Config


class Pv:
    """
    A class representing household photovoltaic system.

    Attributes:
        production (float): The amount of energy generated by photovoltaics expressed in kWh.
    """
    def __init__(self, production: float = 0.0):
        self.production = production

    def get_current_production(self):
        with open(Config.DATA_ENERGY_PRODUCTION, 'r') as f:
            self.production = f.readline()
            return self.production
