import pandas as pd

from lib.config import Config, PhotovoltaicDirection
from lib.file_management import DfManager


class Pv:
    """
    A class representing household photovoltaic system.

    Attributes:
        production (float): The amount of energy generated by photovoltaics expressed in kWh.
        csv_file (CSVFile): The CSVFile class object for csv files management.
        size (float): The size of photovoltaic installation expressed in kWp.
        efficiency (int): The efficiency of photovoltaic installation expressed in percentages.
        direction (PhotovoltaicDirection): The photovoltaic installation: east-west or south.
    """

    def __init__(self,
                 date_column: None | str = None,
                 production: float = 0.0,
                 size: float = 10.0,  # TODO: Not implemented!
                 efficiency: int = 100,  # TODO: Not implemented!
                 direction: PhotovoltaicDirection = PhotovoltaicDirection.EAST_WEST):  # TODO: Not implemented!
        self.production = production
        self.df_manager = DfManager(Config.DATA_ENERGY_PRODUCTION, date_column)
        self.size = size
        self.efficiency = efficiency
        self.direction = direction
        self.date_column = date_column

    def get_production_by_date(self, date_in: pd.Timestamp) -> float:
        return self.df_manager.get_cell_by_date(self.date_column, date_in, "PV gen (kW)")


# Example
# if __name__ == "__main__":
#     pv = Pv(date_column="Date")
#     print(pv.get_production_by_date(pd.to_datetime("01.01.2015 06:00:00")))
